@extends('admin.admin')

@section('title')
    add charge
@endsection
@section('head_css')
<link rel="stylesheet" href="{{asset('backend')}}/assets/js/plugins/datatables/dataTables.bootstrap4.css">
<link rel="stylesheet" href="{{asset('backend')}}/assets/js/plugins/datatables/buttons-bs4/buttons.bootstrap4.min.css">

<link rel="stylesheet" href="{{asset('backend')}}/assets/js/plugins/select2/css/select2.min.css">
@endsection

@section('content')
<div class="content">
    <div class="row">

        <div class="col-md-12">
            <div class="block block-fx-shadow">
                <div class="block-header bg-info-light">All Purchase Orders for {{ date('Y') }}
                    <div class="block-options">
                        <button id="btn-add" name="btn-add" class="btn btn-primary btn-xs" data-toggle="modal" data-target="purchase-block-normal">Add New Purchase Order</button>
                    </div>
                </div>
                <div class="block-content block-content-full">
                    <div class="table-responsive ">
                        <table class="table table-bordered table-striped table-vcenter js-dataTable-buttons">
                            <thead>
                                <th>SN</th>
                                <th>Generated By</th>
                                <th>Supplier</th>
                                <th>Amount</th>
                                <th>Status</th>
                                <th>action</th>
                            </thead>
                            <tbody>
                                @foreach ($purchaseOrder as $item)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$item->generatedBy->fullname}}</td>
                                    <td>{{$item->supplier->name}}</td>
                                    <td>₦ {{$item->amount}}</td>
                                <td> {{ $item->status }}</td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="{{route('charge.edit', $item->id)}}" class="btn btn-sm btn-primary" data-toggle="tooltip" title="Edit">
                                                <i class="fa fa-fw fa-pencil-alt"></i>
                                            </a>
                                            <form action="{{route('charge.destroy', $item->id)}}" method="POST" >
                                                @csrf
                                                    @method('DELETE')
                                                    <button class="btn btn-sm btn-outline-info" data-toggle="tooltip" data-placement="top" title="delete expense" type="submit"><i class="fa fa-times text-danger ml-auto"></i></button>
                                                </form>
                                        </div>
                                    </td>
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 <!-- Pharmacy Modal -->
 <div class="modal" id="purchase-block-normal" tabindex="-1" role="dialog" aria-labelledby="purchase-block-normal" aria-hidden="true" >
    <div class="modal-dialog modal-lg modal-dialog-top" role="document" >
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-light">
                    <h3 class="block-title">Drug Request</h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="fa fa-fw fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content font-size-sm">

                    <div class="table-responsive">
                        <form action="{{route('purchaseOrder.store') }}" method="POST" class="form form-element" onsubmit="return false;">
                            @csrf
                            <div class="form-group">
                                <label for="supplier"></label>
                                <select name="supplier_id" id="supplier" class="form-control form-control-lg" required>
                                    <option>select one</option>
                                    {{ create_option('suppliers', 'id', 'name') }}
                                </select>

                            </div>
                            <table class="table table-bordered table-striped" id="drugs">
                                <thead>
                                <th>Category</th>
                                <th>Subcategory</th>
                                <th>Drug Name/ Form</th>
                                <th>Dosage</th>
                                <th>Instruction</th>

                                <th style="text-align: center;background: #eee">

                                </th>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                        <select  class="js-select2 form-control" style="width: 100%;" data-placeholder="Choose one.." id="category" required>
                                            <option></option>
                                            {{ create_option('drug_classes','id', 'name')}}
                                        </select>
                                    </td>
                                     <td>
                                        <select  class="js-select2 form-control" style="width: 100%;" id="drug" data-placeholder="Choose one.." required>
                                        <option></option>
                                    </select>
                                </td>

                                    <td>

                                        <input type="number" id="quantity" class="form-control form-control-lg"></td>
                                    <td>
                                        <input type="text" id="instruction" class="form-control form-control-lg">
                                    </td>


                                    <td  style="text-align: center">
                                            <a  class="btn btn-success" onclick="rowAdd()">
                                                <i class="fa fa-plus"> Add Drug</i>
                                            </a>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>





                    <button  id="drugSubmit" data-appointment="{{$appointment->id}}" class="btn btn-primary pull-right">Submit</button>
                        </form>

                    </div>
                </div>
                <div class="block-content block-content-full text-right border-top">
                    <button type="button" class="btn btn-sm btn-light" data-dismiss="modal">Close</button>

                </div>
            </div>
        </div>
</div>


@endsection
@section('foot_js')
<script src="{{asset('backend')}}/assets/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{asset('backend')}}/assets/js/plugins/datatables/dataTables.bootstrap4.min.js"></script>
<script src="{{asset('backend')}}/assets/js/plugins/datatables/buttons/dataTables.buttons.min.js"></script>
<script src="{{asset('backend')}}/assets/js/plugins/datatables/buttons/buttons.print.min.js"></script>
<script src="{{asset('backend')}}/assets/js/plugins/datatables/buttons/buttons.html5.min.js"></script>
<script src="{{asset('backend')}}/assets/js/plugins/datatables/buttons/buttons.flash.min.js"></script>
<script src="{{asset('backend')}}/assets/js/plugins/datatables/buttons/buttons.colVis.min.js"></script>

<!-- Page JS Code -->
<script src="{{asset('backend')}}/assets/js/pages/be_tables_datatables.min.js"></script>

@endsection
